project_id = "etfolhinohgmskbfjoyh"

[functions.send-course-email]
verify_jwt = false

[functions.zoom-register-course]
verify_jwt = false

[functions.send-campaign-email]
verify_jwt = false

[functions.create-infinity-payment]
verify_jwt = true

[functions.infinity-payment-callback]
verify_jwt = false
