(function(){
'use strict';
if(window.__PSP_ADMIN_LIVE_DESK_V307__)return;window.__PSP_ADMIN_LIVE_DESK_V307__=true;
const SB_URL='https://etfolhinohgmskbfjoyh.supabase.co',SB_KEY='sb_publishable_LgmfuH2ePiY8fxNGs7nTTA_FSS_oPBw';
let fallback=null,items=[],active=null,loading=false,timer=null;
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>{if(!v)return'—';try{return new Date(v).toLocaleString()}catch(_){return'—'}};
function db(){try{if(typeof sb!=='undefined'&&sb)return sb;if(window.sb)return window.sb;if(window.adminSb)return window.adminSb;if(!fallback&&window.supabase?.createClient)fallback=window.supabase.createClient(SB_URL,SB_KEY,{auth:{storageKey:'pipsepaisa-admin-auth-v2',persistSession:true,autoRefreshToken:true}});return fallback}catch(_){return null}}
async function waitDb(){for(let i=0;i<40;i++){const c=db();if(c)return c;await new Promise(r=>setTimeout(r,100))}return null}
function ago(v){if(!v)return'';const s=Math.max(0,(Date.now()-new Date(v).getTime())/1000);if(s<60)return Math.floor(s)+'s';if(s<3600)return Math.floor(s/60)+'m';if(s<86400)return Math.floor(s/3600)+'h';return Math.floor(s/86400)+'d'}
function initials(x){return String(x||'V').trim().split(/\s+/).slice(0,2).map(a=>a[0]||'').join('').toUpperCase()||'V'}
function css(){if(document.getElementById('adld307css'))return;const s=document.createElement('style');s.id='adld307css';s.textContent=`
#adLiveDesk307{display:none;height:calc(100vh - 250px);min-height:500px}
#adLiveDesk307.open{display:grid;grid-template-columns:340px 1fr;gap:14px}
.adld307-side,.adld307-main{background:var(--bg-card);border:1px solid var(--border);border-radius:14px;overflow:hidden}
.adld307-side{display:flex;flex-direction:column}.adld307-top{padding:13px;border-bottom:1px solid var(--border)}
.adld307-search{width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid var(--border);border-radius:10px;background:var(--bg-elevated);color:var(--text-primary);font-size:11px}
.adld307-list{flex:1;overflow:auto;padding:7px}.adld307-item{padding:10px;border:1px solid transparent;border-radius:10px;cursor:pointer;margin-bottom:5px;display:grid;grid-template-columns:34px 1fr auto;gap:9px}.adld307-item:hover{background:var(--bg-elevated)}.adld307-item.active{border-color:var(--gold);background:rgba(243,149,34,.08)}
.adld307-av{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,var(--gold),#d97706);color:#17110a;font-weight:900;font-size:11px}.adld307-name{font-weight:850;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.adld307-prev,.adld307-meta{font-size:8.5px;color:var(--text-muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}.adld307-time{font-size:8px;color:var(--text-muted)}
.adld307-main{display:flex;flex-direction:column}.adld307-empty{margin:auto;color:var(--text-muted);font-size:11px}.adld307-profile{padding:13px 15px;border-bottom:1px solid var(--border)}.adld307-profile h3{margin:0;font-size:14px}.adld307-grid{display:flex;gap:12px;flex-wrap:wrap;margin-top:5px}.adld307-grid span{font-size:8.5px;color:var(--text-muted)}.adld307-grid b{color:var(--text-primary)}
.adld307-stream{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:8px}.adld307-msg{max-width:76%;padding:8px 11px;border-radius:13px;font-size:10.5px;line-height:1.45}.adld307-msg.visitor{align-self:flex-start;background:var(--bg-elevated);border:1px solid var(--border)}.adld307-msg.ai,.adld307-msg.manager{align-self:flex-end;background:rgba(243,149,34,.12);border:1px solid rgba(243,149,34,.22)}.adld307-msg.note{align-self:center;background:rgba(59,130,246,.08);border:1px dashed rgba(59,130,246,.25)}
.adld307-who{font-size:8px;color:var(--text-muted);margin-bottom:3px}
@media(max-width:900px){#adLiveDesk307.open{grid-template-columns:1fr}.adld307-main{min-height:500px}}
`;document.head.appendChild(s)}
function inject(){
 const w=document.getElementById('adChatsWrap'),a=document.getElementById('actab-chats'),b=document.getElementById('actab-comm');if(!w||!a||!b)return false;css();
 if(!document.getElementById('actab-live307')){const x=document.createElement('button');x.id='actab-live307';x.textContent='🤖 Live Desk / AI Chats';x.style.cssText='padding:9px 18px;border:1px solid var(--border);border-radius:10px;background:transparent;color:var(--text-primary);font-weight:700;cursor:pointer';x.onclick=show;b.insertAdjacentElement('afterend',x)}
 if(!document.getElementById('adLiveDesk307')){const d=document.createElement('div');d.id='adLiveDesk307';d.innerHTML=`<section class="adld307-side"><div class="adld307-top"><b>All Website Chats</b><div style="font-size:9px;color:var(--text-muted);margin:3px 0 8px">FreeCourse2 + all Live Desk conversations</div><input id="adld307Search" class="adld307-search" placeholder="Search name, email, WhatsApp, source..."></div><div id="adld307List" class="adld307-list"><div class="adld307-empty">Loading…</div></div></section><section id="adld307Main" class="adld307-main"><div class="adld307-empty">Select a chat to view full conversation.</div></section>`;w.appendChild(d);document.getElementById('adld307Search').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,250)}}
 return true;
}
function show(){if(!inject())return;document.getElementById('aTabChats').style.display='none';document.getElementById('aTabComm').style.display='none';document.getElementById('adLiveDesk307').classList.add('open');const c=document.getElementById('actab-live307');c.style.background='linear-gradient(135deg,#f59e0b,#d97706)';c.style.color='#0a0e1a';c.style.border='none';load()}
function hide(){document.getElementById('adLiveDesk307')?.classList.remove('open');const c=document.getElementById('actab-live307');if(c){c.style.background='transparent';c.style.color='var(--text-primary)';c.style.border='1px solid var(--border)'}}
async function load(){if(loading)return;loading=true;const box=document.getElementById('adld307List');if(box)box.innerHTML='<div class="adld307-empty">Loading chats…</div>';try{const c=await waitDb(),q=document.getElementById('adld307Search')?.value.trim()||null,r=await c.rpc('psp_admin_live_chat_inbox_v307',{p_search:q,p_limit:800});if(r.error)throw r.error;items=Array.isArray(r.data)?r.data:[];renderList()}catch(e){if(box)box.innerHTML='<div style="padding:14px;color:#dc2626;font-size:10px">'+esc(e.message||e)+'</div>'}finally{loading=false}}
function renderList(){const box=document.getElementById('adld307List');if(!box)return;if(!items.length){box.innerHTML='<div class="adld307-empty" style="padding:18px">No chats found.</div>';return}box.innerHTML=items.map(x=>`<div class="adld307-item ${active&&active.id===x.id?'active':''}" data-id="${esc(x.id)}"><div class="adld307-av">${esc(initials(x.visitor_name||x.email))}</div><div><div class="adld307-name">${esc(x.visitor_name||x.email||'Visitor')}</div><div class="adld307-prev">${esc(x.last_message_preview||'Conversation')}</div><div class="adld307-meta">${esc(x.source||'Direct')} · ${esc(x.current_page||x.first_page||'/')}</div></div><div class="adld307-time">${esc(ago(x.last_message_at||x.updated_at||x.created_at))}</div></div>`).join('');box.onclick=e=>{const r=e.target.closest('[data-id]');if(r)openChat(r.dataset.id)}}
async function openChat(id){active=items.find(x=>String(x.id)===String(id))||{id};renderList();const main=document.getElementById('adld307Main');main.innerHTML='<div class="adld307-empty">Loading conversation…</div>';try{const c=await waitDb(),r=await c.rpc('psp_admin_live_chat_messages_v307',{p_conversation_id:String(id),p_limit:1500});if(r.error)throw r.error;renderChat(Array.isArray(r.data)?r.data:[])}catch(e){main.innerHTML='<div class="adld307-empty" style="color:#dc2626">'+esc(e.message||e)+'</div>'}}
function renderChat(msgs){const c=active||{},main=document.getElementById('adld307Main');main.innerHTML=`<div class="adld307-profile"><h3>${esc(c.visitor_name||c.email||'Visitor')}</h3><div class="adld307-grid"><span>Email: <b>${esc(c.email||'—')}</b></span><span>WhatsApp: <b>${esc(c.whatsapp||'—')}</b></span><span>Source: <b>${esc([c.source,c.campaign].filter(Boolean).join(' / ')||'Direct')}</b></span><span>Page: <b>${esc(c.first_page||c.current_page||'—')}</b></span></div></div><div id="adld307Stream" class="adld307-stream">${msgs.length?msgs.map(m=>{const t=String(m.sender_type||'visitor').toLowerCase(),cl=t==='visitor'?'visitor':t==='note'?'note':t==='ai'?'ai':'manager';return `<div class="adld307-msg ${cl}"><div class="adld307-who">${esc(m.sender_name||t)} · ${esc(dt(m.created_at))}</div>${esc(m.body||'')}</div>`}).join(''):'<div class="adld307-empty">No messages.</div>'}</div>`;const s=document.getElementById('adld307Stream');if(s)s.scrollTop=s.scrollHeight}
function hook(){if(typeof window.aCommSwitch==='function'&&!window.__ADLD307C){window.__ADLD307C=1;const o=window.aCommSwitch;window.aCommSwitch=function(){hide();return o.apply(this,arguments)}}if(typeof window.renderAdminChats==='function'&&!window.__ADLD307R){window.__ADLD307R=1;const o=window.renderAdminChats;window.renderAdminChats=function(){const r=o.apply(this,arguments);setTimeout(inject,0);return r}}}
function init(){hook();if(document.getElementById('page-chats')?.classList.contains('active'))setTimeout(inject,50);setTimeout(init,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();