const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../admin-mobile-v441.js'),'utf8');
function harness({mobile=true,loggedIn=true}={}){
 const events={},docEvents={},frames=[],calls=[],observers=[];let active='dashboard',desktopCalls=0;
 const make=(text='')=>{const classes=new Set(),attributes={};return {textContent:text,children:[],value:'',hidden:false,isConnected:true,style:{},classList:{contains:x=>classes.has(x),add:x=>classes.add(x),remove:x=>classes.delete(x),toggle(x,on){const v=on===undefined?!classes.has(x):on;v?classes.add(x):classes.delete(x);return v}},setAttribute(k,v){attributes[k]=v},getAttribute:k=>attributes[k]??null,removeAttribute(k){delete attributes[k]},addEventListener(k,fn){(this.events??={})[k]=fn},appendChild(x){this.children.push(x)},before(){},insertAdjacentHTML(){},querySelector:()=>null,querySelectorAll:()=>[],getClientRects:()=>[{}],matches:()=>false,focus(){c.document.activeElement=this}}};
 const body=make(),main=make(),sidebar=make(),content=make(),toggle=make(),brand=make(),menu=make(),closeBtn=make(),search=make(),empty=make(),page=make();page.id='page-dashboard';page.classList.add('page');
 const menus=['dashboard','users','paymentreqs','teamperformance','revenue','settings'].map(k=>{const el=make(k);el.dataset={page:k};return el});
 const buttons=['home','users','pay','team','more'].map(k=>{const el=make();el.dataset={mobileNav:k};return el});let nav;
 toggle.onclick=()=>desktopCalls++;
 sidebar.querySelector=s=>s==='.brand'?brand:s==='.menu'?menu:s==='.am441-close'?closeBtn:null;sidebar.querySelectorAll=s=>s==='.menu-item'?menus:[closeBtn,search];
 const table=make(),cells=[make('Hassan'),make('hassan@example.test')],row=make();cells.forEach(x=>{x.tagName='TD';x.colSpan=1;x.rowSpan=1});row.children=cells;table.querySelectorAll=s=>s==='thead th'?[make('User'),make('Email')]:[row];page.querySelectorAll=()=>[table];
 const c={console,currentAdmin:loggedIn?{id:'admin'}:null,innerHeight:800,visualViewport:{height:800,addEventListener(){}},matchMedia:()=>({matches:mobile}),getComputedStyle:x=>({display:x.hidden?'none':'flex'}),requestAnimationFrame(fn){frames.push(fn);return frames.length},addEventListener(k,fn){(events[k]??=[]).push(fn)},MutationObserver:class{constructor(fn){observers.push(fn)}observe(){}},document:{readyState:'complete',body,activeElement:toggle,addEventListener(k,fn){(docEvents[k]??=[]).push(fn)},querySelector(s){if(s==='#content>.page.active'){page.id='page-'+active;return page}if(s==='#sidebar')return sidebar;if(s==='.main')return main;if(s==='#content')return content;if(s==='.mobile-toggle')return toggle;if(s==='.topbar')return make();if(s==='#adminMobileSearch')return search;if(s==='#adminMobileEmpty')return empty;const m=s.match(/data-page="([^"]+)"/);return m?menus.find(x=>x.dataset.page===m[1])||null:null},createElement(tag){const el=make();if(tag==='nav'){nav=el;el.querySelectorAll=()=>buttons;el.querySelector=()=>buttons[4]}return el}},showPage(target){calls.push(target);active=target}};
 c.window=c;vm.createContext(c);vm.runInContext(source,c);
 const flush=()=>{while(frames.length)frames.shift()()};
 return {c,body,main,sidebar,search,empty,menus,buttons,table,row,cells,closeBtn,toggle,events,docEvents,calls,flush,desktopCalls:()=>desktopCalls,mobile(v){mobile=v},setActive(v){active=v},setRoute(fn){c.showPage=fn},navClick(key){const b=buttons.find(x=>x.dataset.mobileNav===key);nav.events.click({target:{closest:()=>b}});flush()},input(q){search.value=q;search.events.input()},emit(k){for(const fn of events[k]||[])fn();flush()}};
}
test('mobile navigation is hidden before authentication and logout closes the menu',()=>{const h=harness({loggedIn:false});assert.equal(h.body.classList.contains('am441-ready'),false);h.navClick('more');assert.equal(h.sidebar.classList.contains('open'),false);h.c.currentAdmin={id:'admin'};h.emit('psp-admin-auth-ready');h.navClick('more');assert.equal(h.sidebar.classList.contains('open'),true);assert.equal(h.main.inert,true);h.c.currentAdmin=null;h.emit('psp-admin-auth-closed');assert.equal(h.sidebar.classList.contains('open'),false);assert.equal(h.main.inert,false);assert.equal(h.body.classList.contains('am441-ready'),false)});
test('bottom navigation reflects the visible page while a lazy route is pending',async()=>{const h=harness();let resolve;h.setRoute(()=>new Promise(r=>resolve=r));h.navClick('users');assert.equal(h.buttons[0].getAttribute('aria-current'),'page');assert.equal(h.buttons[1].getAttribute('aria-current'),null);h.setActive('users');resolve();await Promise.resolve();h.flush();assert.equal(h.buttons[1].getAttribute('aria-current'),'page')});
test('More search filters existing tools and closing restores every menu item',()=>{const h=harness();h.navClick('more');h.input('users');assert.equal(h.menus.filter(x=>!x.classList.contains('am441-filtered')).length,1);h.input('unknown tool');assert.equal(h.empty.hidden,false);h.closeBtn.onclick();assert.equal(h.menus.some(x=>x.classList.contains('am441-filtered')),false);assert.equal(h.search.value,'');assert.equal(h.c.document.activeElement,h.toggle)});
test('desktop keeps its existing menu toggle and no mobile card metadata is written',()=>{const h=harness({mobile:false});h.toggle.onclick();assert.equal(h.desktopCalls(),1);h.setActive('users');h.emit('psp-admin-workspace-ready');assert.equal(h.row.classList.contains('am441-record'),false);assert.equal(h.menus[0].getAttribute('tabindex'),null)});
test('mobile User cards label mounted cells without replacing data or losing actions',()=>{const h=harness();h.setActive('users');h.emit('psp-admin-workspace-ready');assert.equal(h.row.classList.contains('am441-record'),true);assert.equal(h.cells[1].getAttribute('data-mobile-label'),'Email');assert.equal(h.cells[1].textContent,'hassan@example.test');h.cells[1].colSpan=2;h.emit('psp-admin-workspace-ready');assert.equal(h.row.classList.contains('am441-record'),false)});
test('keyboard hides bottom navigation only while a field is being edited',()=>{const h=harness();h.c.document.activeElement={matches:()=>true};h.c.visualViewport.height=450;h.docEvents.focusin[0]();assert.equal(h.body.classList.contains('am441-keyboard'),true);h.c.document.activeElement={matches:()=>false};h.docEvents.focusout[0]();h.flush();assert.equal(h.body.classList.contains('am441-keyboard'),false)});
