-- PipSePaisa V475 — security hardening without UI/business-flow changes.
-- Applied to production 2026-10-07.
--
-- 1) Close direct browser access to internal SECURITY DEFINER helpers.
-- 2) Keep signed-in access/VIP RPCs unavailable to anon.
-- 3) Add a durable authenticated rate limit for the server-side AI endpoint.

begin;

revoke all on function public.psp_course_paid_event_at_v371(uuid) from public, anon, authenticated;
revoke all on function public.psp_team_current_assignment_at_v371(uuid,text,text) from public, anon, authenticated;
revoke all on function public.psp_team_member_at_event_v371(uuid,timestamptz) from public, anon, authenticated;

grant execute on function public.psp_course_paid_event_at_v371(uuid) to service_role;
grant execute on function public.psp_team_current_assignment_at_v371(uuid,text,text) to service_role;
grant execute on function public.psp_team_member_at_event_v371(uuid,timestamptz) to service_role;

revoke all on function public.psp_get_access_snapshot_v467() from public, anon;
revoke all on function public.psp_get_official_vip_plan_v458() from public, anon;

grant execute on function public.psp_get_access_snapshot_v467() to authenticated, service_role;
grant execute on function public.psp_get_official_vip_plan_v458() to authenticated, service_role;

create table if not exists public.psp_ai_rate_v475(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists psp_ai_rate_v475_user_created_idx
  on public.psp_ai_rate_v475(user_id,created_at desc);

alter table public.psp_ai_rate_v475 enable row level security;
revoke all on table public.psp_ai_rate_v475 from public, anon, authenticated;
grant select,insert,delete on table public.psp_ai_rate_v475 to service_role;

create or replace function public.psp_ai_rate_limit_v475()
returns boolean
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_uid uuid := auth.uid();
  v_10m integer := 0;
  v_24h integer := 0;
begin
  if v_uid is null then
    raise exception 'Authentication required.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_uid::text,475)
  );

  select
    count(*) filter (where r.created_at >= now() - interval '10 minutes'),
    count(*)
  into v_10m,v_24h
  from public.psp_ai_rate_v475 r
  where r.user_id=v_uid
    and r.created_at >= now() - interval '24 hours';

  if v_10m >= 10 or v_24h >= 60 then
    return false;
  end if;

  insert into public.psp_ai_rate_v475(user_id) values (v_uid);

  delete from public.psp_ai_rate_v475
  where created_at < now() - interval '2 days';

  return true;
end;
$function$;

revoke all on function public.psp_ai_rate_limit_v475() from public, anon;
grant execute on function public.psp_ai_rate_limit_v475() to authenticated, service_role;

commit;
